version: '3'

services:
  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront

  todofront:
    image: todofrontend
    restart: always
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:80

  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:80